language: objective-c
osx_image: xcode8

env:
  - >
    xcode_project=Progressable.xcodeproj
    xcode_scheme=ProgressableTests
    xcode_sdk=iphonesimulator
    xcode_platform="platform=iOS Simulator,name=iPhone 6"

script:
  - >
    set -o pipefail && xcodebuild
    -project ${xcode_project}
    -scheme ${xcode_scheme}
    -sdk ${xcode_sdk}
    -destination "${xcode_platform}" test | xcpretty -c
